version: "3.8"
services:
  mysql:
    container_name: mysql
    image: michelle548129/theimpossiblequiz-db:latest
    build: ./db
    volumes:
      - type: volume
        source: app-vol
        target: /var/lib/mysql
    networks:
      - app-net
    environment:
      MYSQL_ROOT_PASSWORD: "password123"
      MYSQL_DATABASE: app-db
  flask-app:
    container_name: flask-app
    image: michelle548129/theimpossiblequiz-app:v2
    build: ./flask-app
    networks:
      - app-net
    environment:
      MYSQL_ROOT_PASSWORD: "password123"
      SECRET_KEY: "this is my secret key"
    depends_on:
      - "mysql"
  nginx:
    container_name: nginx
    image: nginx:latest
    networks:
      - app-net
    ports:
      - target: 80
        published: 80
        protocol: tcp
    volumes:
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/nginx.conf
    depends_on:
      - "flask-app"
volumes:
  app-vol:
networks:
  app-net:
   # driver: overlay (uncomment when deploying via docker stack)